openapi: 3.0.0
info:
  title: efishery_test
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: http://localhost:3001
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /user:
    post:
      tags:
        - default
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone: '08123123123'
                name: oky
                role: admin
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /token/create:
    post:
      tags:
        - default
      summary: Generate Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone: '08123123123'
                password: '@veB'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /token/verify:
    post:
      tags:
        - default
      summary: Verify Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                token: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib2t5Iiwicm9sZSI6ImFkbWluIiwicGhvbmUiOiIwODEyMzEyMzEyMyIsInRpbWVzdGFtcCI6IjIwMjEtMTItMDlUMDc6NDM6MzMuOTk5WiIsImlhdCI6MTYzOTAzNTgzMCwiZXhwIjoxNjM5MTIyMjMwfQ.CGubVOQSjYsas3GjX4_C5rZYJv3OKeID-QPn6AZx4yI
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /commodity/list:
    get:
      tags:
        - default
      summary: Commodity List
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /commodity/aggregate:
    get:
      tags:
        - default
      summary: Commodity Aggregate
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /token/introspect:
    get:
      tags:
        - default
      summary: Introspect Token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
